### ISSUE TITLE
Incorrect `Combustor` implementation

### ISSUE THREAD

**Issue by CousinZe** [Pr47/Project-47#22]
Let us go over one of the basic ideas of Pr47 asynchronous implementation: when an asynchronous FFI function wants to access the VM, it must acquire the running permission first, in order not corrupting other tasks. However, according to the current `Combustor` implementation:

https://github.com/Pr47/Pr47/blob/6d2d9ca5c58ec475746704ad01b2189aa5859ccb/pr47-core/src/vm/al31f/mod.rs#L55

This would allow one permission to be shared across several places, which is definitely inkorrect.

**Comment by chuigda** [comment]
Thanks for reporting this. I'll take a deeper look. Also, give me a hand @SchrodingerZhu.

**Comment by chuigda** [comment]
Formal verification with type rich programming, genius design.

**Comment by CousinZe** [comment]
> genius design.

Bullshit.

**Comment by chuigda** [comment]
Closed as resolved.
