### ISSUE TITLE
`Alloc` trait leaks AL31FM2 internals

### ISSUE THREAD

**Issue by CousinZe** [Pr47/Project-47#36]
Here, `Alloc` trait is directly denoted:
https://github.com/Pr47/Pr47/blob/233b8c20483c1225a20061300ffb02b93f38bd91/pr47-core/src/ffi/async_fn.rs#L20-L24

However, `Alloc` trait is part of AL31F:
https://github.com/Pr47/Pr47/blob/233b8c20483c1225a20061300ffb02b93f38bd91/pr47-core/src/vm/al31f/alloc.rs#L11-L37

What's more, the `add_stack` and `remove_stack` methods directly leak the implemenational details.

**Comment by chuigda** [comment]
I think we can use the `VMContext` trait APIs from `sync_fn` for `VMDataTrait`, thus avoid exposing the actual `Alloc` to exterior.
